version: "3"
services:
  postgres:
    image: postgres:11.6
    container_name: "postgres"
    environment:
      POSTGRES_USER: vue
      POSTGRES_PASSWORD: vue
      POSTGRES_DB: vue
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "15432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
